# Generated by Django 4.0 on 2021-12-28 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='version',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
