# Generated by Django 4.0 on 2021-12-28 16:08
import sys

from django.db import migrations


def add_version_031(apps, schema_editor):
    VERSION = apps.get_model("generic", "Version")
    db_alias = schema_editor.connection.alias

    v031 = VERSION.objects.using(db_alias).filter(
        version='0.3.1').first()
    if not v031:
        VERSION.objects.using(db_alias).create(
            version='0.3.1',
            notes='Update version created field to auto now add\r\nAdd user ui login and base home pages for users and gms')

def reverse_add_version_031(apps, schema_editor):
    VERSION = apps.get_model("generic", "Version")
    db_alias = schema_editor.connection.alias

    VERSION.objects.using(db_alias).filter(version='0.3.1').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('generic', '0002_alter_version_created'),
    ]

    operations = [
        migrations.RunPython(add_version_031,
                             reverse_add_version_031),
    ] if 'test' not in sys.argv else []
