# Generated by Django 3.2 on 2021-06-11 21:59

from django.db import migrations, models
import django.db.models.deletion
import empires.stdfields.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('generic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MagicSubSchool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
            ],
            options={
                'db_table': 'magicsubschool',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Deity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('pronunciation', models.CharField(max_length=64)),
                ('spheres', models.CharField(max_length=128)),
                ('description', models.TextField()),
            ],
            options={
                'db_table': 'deity',
            },
        ),
        migrations.CreateModel(
            name='MagicSchool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
            ],
            options={
                'db_table': 'magicschool',
            },
        ),
        migrations.CreateModel(
            name='Spell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('level', models.PositiveIntegerField()),
                ('call', models.CharField(max_length=128)),
                ('description', models.TextField()),
                ('duration', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='generic.durationtype')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='magic.magicschool')),
                ('specialty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='magic.magicsubschool')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='generic.targettype')),
            ],
            options={
                'db_table': 'spell',
                'unique_together': {('name', 'school', 'specialty')},
            },
        ),
        migrations.CreateModel(
            name='SpellDuration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timetype', empires.stdfields.fields.EnumCharField(choices=[('S', 'Second'), ('M', 'Minute'), ('H', 'Hour'), ('D', 'Day')], max_length=1)),
                ('count', models.IntegerField()),
                ('spell', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='magic.spell')),
            ],
            options={
                'db_table': 'spell_duration',
            },
        ),
    ]
