# Generated by Django 3.2 on 2021-12-12 22:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('magic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spell',
            name='level',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='spellduration',
            name='count',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.CreateModel(
            name='SpellCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subschool_order', models.PositiveIntegerField()),
                ('level', models.PositiveSmallIntegerField()),
                ('xp_cost', models.PositiveSmallIntegerField()),
                ('charclass', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='charclass.charclass')),
            ],
            options={
                'db_table': 'spellcost',
                'unique_together': {('subschool_order', 'level', 'charclass')},
            },
        ),
    ]
