# Generated by Django 3.2 on 2021-06-12 00:32

from django.db import migrations, models
import django.db.models.deletion
import empires.stdfields.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('generic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArmourType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
                ('points', models.IntegerField()),
                ('slots', models.IntegerField()),
                ('worn', models.IntegerField()),
            ],
            options={
                'db_table': 'armourtype',
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
                ('equipmenttype', empires.stdfields.fields.EnumCharField(choices=[('MAGIC', 'Magic'), ('SKILL', 'Skill'), ('REG', 'Regular'), ('AMMO', 'Ammo')], max_length=5)),
            ],
            options={
                'db_table': 'equipment',
            },
        ),
        migrations.CreateModel(
            name='Weapon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('weapontype', empires.stdfields.fields.EnumCharField(choices=[('R', 'Ranged'), ('S', 'SHORT'), ('L', 'Long'), ('2H', 'Two-Handed')], max_length=2)),
            ],
            options={
                'db_table': 'weapon',
            },
        ),
        migrations.CreateModel(
            name='ArmourType_Effect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('armourtype', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='equipment.armourtype')),
                ('effect', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='generic.effect')),
            ],
            options={
                'db_table': 'armourtype_effect',
                'unique_together': {('armourtype', 'effect')},
            },
        ),
    ]
