# Generated by Django 3.2 on 2021-06-22 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gameevent',
            name='location',
        ),
        migrations.RemoveField(
            model_name='shardevent',
            name='location',
        ),
        migrations.DeleteModel(
            name='Location',
        ),
    ]
