# Generated by Django 3.2 on 2021-12-12 23:01

from django.db import migrations, models
import django.db.models.deletion
import empires.stdfields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('skill', '0001_initial'),
        ('magic', '0002_auto_20211212_1827'),
        ('character', '0002_add_user_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='bank_iron',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='character',
            name='coin_iron',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='character',
            name='death_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='character',
            name='event_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='character',
            name='is_dead',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='character',
            name='level',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='character',
            name='xp_earned',
            field=models.PositiveSmallIntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='character',
            name='xp_spent',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='charactershardxp',
            name='xp_assigned',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.CreateModel(
            name='Character_Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveSmallIntegerField()),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='character.character')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='skill.skill')),
            ],
            options={
                'db_table': 'character_skill',
                'unique_together': {('character', 'skill')},
            },
        ),
        migrations.CreateModel(
            name='Character_SpellSlots',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveSmallIntegerField()),
                ('slots', models.PositiveSmallIntegerField()),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='character.character')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='magic.magicschool')),
                ('specialty', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='magic.magicsubschool')),
            ],
            options={
                'db_table': 'character_spellslots',
                'unique_together': {('character', 'school', 'specialty', 'level')},
            },
        ),
        migrations.CreateModel(
            name='Character_Skill_Hand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hand', empires.stdfields.fields.EnumCharField(choices=[('L', 'Left'), ('R', 'Right')], max_length=1)),
                ('level', models.PositiveSmallIntegerField()),
                ('character_skill', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='character.character_skill')),
            ],
            options={
                'db_table': 'character_skill_hand',
                'unique_together': {('character_skill', 'hand')},
            },
        ),
        migrations.CreateModel(
            name='Character_AlchemySlots',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveSmallIntegerField()),
                ('slots', models.PositiveSmallIntegerField()),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='character.character')),
                ('specialty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='alchemy.alchemyspecialty')),
            ],
            options={
                'db_table': 'character_alchemyslots',
                'unique_together': {('character', 'specialty', 'level')},
            },
        ),
    ]
