# Generated by Django 4.0 on 2022-01-15 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('magic', '0002_auto_20211212_1827'),
        ('character', '0003_auto_20211212_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character_spellslots',
            name='specialty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='magic.magicsubschool'),
        ),
    ]
