# Generated by Django 4.0 on 2022-01-15 23:06

from django.db import migrations
import empires.stdfields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0004_alter_character_spellslots_specialty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='chartype',
            field=empires.stdfields.fields.EnumCharField(choices=[('PC', 'Player Character'), ('NPC', 'Non-Player Character'), ('BOSS', 'Named NPC')], max_length=4, verbose_name='Character Type'),
        ),
    ]
