# Generated by Django 3.2 on 2021-06-11 23:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
                ('attribute_points', models.PositiveIntegerField()),
                ('description', models.TextField()),
                ('costume_req', models.TextField(blank=True, null=True)),
                ('costume_sugg', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'race',
            },
        ),
        migrations.CreateModel(
            name='SubRace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
                ('attribute_points', models.PositiveIntegerField()),
                ('description', models.TextField()),
                ('costume_req', models.TextField()),
                ('costume_sugg', models.TextField()),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='race.race')),
            ],
            options={
                'db_table': 'subrace',
            },
        ),
    ]
