# Generated by Django 3.2 on 2021-12-12 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('race', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='race',
            name='attribute_points',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='subrace',
            name='attribute_points',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
