# Generated by Django 3.2 on 2021-06-11 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CharClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
                ('base_body', models.IntegerField()),
                ('max_armour', models.IntegerField()),
                ('description', models.TextField()),
            ],
            options={
                'db_table': 'class',
            },
        ),
    ]
