# Generated by Django 3.2 on 2021-12-13 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charclass', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charclass',
            name='base_body',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='charclass',
            name='max_armour',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
