# Generated by Django 3.2 on 2021-06-11 22:33

from django.db import migrations, models
import django.db.models.deletion
import empires.stdfields.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('generic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alchemy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
                ('level', models.IntegerField()),
                ('call', models.CharField(max_length=128)),
                ('description', models.TextField()),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='generic.deliverymethod')),
                ('duration', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='generic.durationtype')),
            ],
            options={
                'db_table': 'alchemy',
            },
        ),
        migrations.CreateModel(
            name='AlchemySpecialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
            ],
            options={
                'db_table': 'alchemyspecialty',
            },
        ),
        migrations.CreateModel(
            name='AlchemyDuration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timetype', empires.stdfields.fields.EnumCharField(choices=[('S', 'Second'), ('M', 'Minute'), ('H', 'Hour'), ('D', 'Day')], max_length=1)),
                ('count', models.IntegerField()),
                ('alchemy', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='alchemy.alchemy')),
            ],
            options={
                'db_table': 'alchemy_duration',
            },
        ),
        migrations.AddField(
            model_name='alchemy',
            name='specialty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='alchemy.alchemyspecialty'),
        ),
        migrations.AddField(
            model_name='alchemy',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='generic.targettype'),
        ),
    ]
