# Generated by Django 3.2 on 2021-12-13 02:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('charclass', '0002_auto_20211212_2205'),
        ('alchemy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alchemy',
            name='level',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='alchemyduration',
            name='count',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.CreateModel(
            name='AlchemyCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveSmallIntegerField()),
                ('xp_cost', models.PositiveSmallIntegerField()),
                ('charclass', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='charclass.charclass')),
            ],
            options={
                'db_table': 'alchemycost',
                'unique_together': {('level', 'charclass')},
            },
        ),
    ]
