# Generated by Django 3.2 on 2021-06-11 23:55

from django.db import migrations, models
import django.db.models.deletion
import empires.stdfields.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('charclass', '0001_initial'),
        ('race', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RacialSkillType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
            ],
            options={
                'db_table': 'racialskilltype',
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('skilltype', empires.stdfields.fields.EnumCharField(choices=[('RACE', 'Racial'), ('CLASS', 'Class'), ('WEAPON', 'Weapon'), ('STUDY', 'Academic'), ('MIND', 'Mental'), ('MAGIC', 'Magic'), ('CRAFT', 'Crafting'), ('JOB', 'Profession'), ('GEN', 'General'), ('STRIKE', 'Strike'), ('MOVE', 'Maneuver'), ('STANCE', 'Stance')], max_length=6)),
                ('multiple', models.PositiveSmallIntegerField()),
                ('call', models.CharField(blank=True, max_length=128, null=True)),
                ('description', models.TextField()),
            ],
            options={
                'db_table': 'skill',
                'unique_together': {('name', 'skilltype')},
            },
        ),
        migrations.CreateModel(
            name='SkillCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xp_cost', models.PositiveSmallIntegerField()),
                ('charclass', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='charclass.charclass')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='skill.skill')),
            ],
            options={
                'db_table': 'skillcost',
                'unique_together': {('skill', 'charclass')},
            },
        ),
        migrations.CreateModel(
            name='Skill_RacialSkillType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('racialskilltype', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='skill.racialskilltype')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='skill.skill')),
            ],
            options={
                'db_table': 'skill_racialskilltype',
                'unique_together': {('skill', 'racialskilltype')},
            },
        ),
        migrations.CreateModel(
            name='Race_RacialSkillType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.IntegerField()),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='race.race')),
                ('racialskilltype', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='skill.racialskilltype')),
                ('subrace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='race.subrace')),
            ],
            options={
                'db_table': 'race_racialskilltype',
                'unique_together': {('race', 'subrace', 'racialskilltype')},
            },
        ),
    ]
