# Generated by Django 3.2 on 2021-12-12 23:01

from django.db import migrations, models
import django.db.models.deletion
import empires.stdfields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('skill', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attacktype', empires.stdfields.fields.EnumCharField(choices=[('MANEUVER', 'Maneuver'), ('STANCE', 'Stance'), ('STRIKE', 'Strike')], max_length=8)),
                ('name', models.CharField(max_length=32, unique=True)),
            ],
            options={
                'db_table': 'attacktype',
                'unique_together': {('attacktype', 'name')},
            },
        ),
        migrations.CreateModel(
            name='HandedSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to='skill.skill')),
            ],
            options={
                'db_table': 'handedskill',
            },
        ),
        migrations.CreateModel(
            name='AttackCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('xp_cost', models.PositiveSmallIntegerField()),
                ('attack', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='skill.skill')),
                ('charclass', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='charclass.charclass')),
            ],
            options={
                'db_table': 'attackcost',
                'unique_together': {('attack', 'level', 'charclass')},
            },
        ),
        migrations.CreateModel(
            name='Attack_SpecialType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attack', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='skill.skill')),
                ('specialtype', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='skill.specialtype')),
            ],
            options={
                'db_table': 'attack_specialtype',
                'unique_together': {('attack', 'specialtype')},
            },
        ),
    ]
